config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "restaurants#index"
  resources :restaurants, only: [:index, :new, :create, :show] do 
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, presence: true, :numericality => { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :category, :address, :phone_number)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>All Restaurants</h1>
  <ul>
    <% @restaurants.each do |restaurant| %>
    <li> <%= link_to restaurant.name, restaurant_path(restaurant) %> </li>
    <% end %>
  </ul>
  <%= link_to "Add a Restaurant", new_restaurant_path %>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h2 class="text-center m-4">New Restaurant Form</h2>
  <%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"] %>
  <%= f.input :phone_number %>
  <%= f.submit "Submit new restaurant", class: "btn btn-primary" %>
  <% end %>
  <%= link_to "Cancel", restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h2 class="m-4"> <%= @restaurant.name %> </h2>
  <p> address : <%= @restaurant.address %> </p>
  <p> category : <%= @restaurant.category %> </p>
  <p> phone_number : <%= @restaurant.phone_number %> </p>
  <%= link_to "Index", restaurants_path %>
  <h3 class="m-4">Reviews</h3>
  <ul>
    <% @restaurant.reviews.each do |review| %>
    <li> <%= review.content %> <strong>Note:</strong> <%= review.rating %>/5 </li>
    <% end %>
  </ul>
  <%= link_to "Add Review", new_restaurant_review_path(@restaurant) %>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<div class="container">
  <h2 class="text-center m-4">New Review Form</h2>

  <%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.submit "Submit new restaurant", class: "btn btn-primary" %>
  <% end %>

  <%= link_to "Cancel", restaurant_path(@restaurant) %>
</div>